### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jbull477/tc-359-project8#1]
It looks like the select input is resetting each time the form submits, while it's specified in the project criteria that `every form field should always show the current parameters`. [This example](https://gist.github.com/chrisvfritz/e36ba5ebf01f86537388) may help you figure out how you can fix this problem.

Another issue I'm seeing is that while the date input has a spot to specify the day, it looks like all holidays for the entire month are being served. I think that violates the rule `affect the data on the page through the API, in a way that seems logical to visitors`, so I'd like to see that fixed.

Let me know when the code is updated and I'll take another look.

**Comment by jbull477** [comment]
This should be fixed now.  I did not run into the first problem you mentioned though.  I even had a couple of other people try it.

**Comment by chrisvfritz** [comment]
The second one seems fixed, but I do still see the first issue. I'm able to reproduce it by changing the country to BE, for example, then hitting the submit button. When the results are shown, the select has reset back to US. Let me know if you're still having trouble reproducing and I'll be happy to hop on a screenshare.

**Comment by jbull477** [comment]
Alright, now it is really fixed!

**Comment by chrisvfritz** [comment]
:+1: Much better! I also see some inconsistent indentation, especially in `app.rb`, that I'd like fixed in all future projects, but this time can slide. See details below.

## Points of improvement for future projects

### Ruby indentation

The standard indentation for Ruby (`.rb`) files is actually with two-space soft-tabs rather than hard-tabs. See if you can update your text editor to use two-space soft-tabs for all Ruby files. If you have trouble figuring it out, [this page may be helpful](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md). If it's not, just let me know and I'll be happy to point you in the right direction.

### Consistent indentation

For non-Ruby files, I _prefer_ two-space tabs, but as long as you're consistently using a single kind of indentation (rather than mixed spaces and hard-tabs as in these files), then I'm fine.
